# Generated by Django 5.2.10 on 2026-01-28 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='start_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Anchor date for billing calculations.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_interval_months',
            field=models.PositiveSmallIntegerField(default=1, help_text='For custom billing: every N months. Auto-set for monthly/yearly.'),
        ),
    ]
