# Generated by Django 5.2.10 on 2026-01-28 14:00

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_subscription_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-transaction_date', '-id']},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
        migrations.AddField(
            model_name='expense',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='When the expense actually happened.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='AUD', max_length=3),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='AUD', max_length=3),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['transaction_date'], name='subscriptio_transac_1c0af1_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'transaction_date'], name='subscriptio_user_id_1ec644_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_2a19e8_idx'),
        ),
    ]
