# Generated by Django 5.2.10 on 2026-01-29

from django.db import migrations, models


def populate_expense_name(apps, schema_editor):
    Expense = apps.get_model("subscriptions", "Expense")
    for expense in Expense.objects.select_related("subscription").all():
        if expense.name:
            continue
        if expense.subscription_id and expense.subscription:
            name = expense.subscription.name
        else:
            name = "Manual expense"
        Expense.objects.filter(pk=expense.pk).update(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_alter_expense_options_remove_expense_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.RunPython(populate_expense_name, migrations.RunPython.noop),
    ]
